# Numpy

In [ ]:
import numpy as np

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
arr = np.random.randint(0, 20, (4, 7))
print("Original Array:\n", arr)

def normalize(matrix):
  norm = np.linalg.norm(arr)
  matrix = matrix/norm
  return matrix

normalized_matrix = normalize(arr)

print("\nNormalized Array:\n", normalized_matrix)

Original Array:
 [[ 2 13 13  2 15 14  8]
 [ 7  5 12 16  1  0 10]
 [12 14 12 15 18 11  6]
 [19 17 17 19  9 13 16]]

Normalized Array:
 [[0.03014428 0.19593785 0.19593785 0.03014428 0.22608213 0.21100999
  0.12057714]
 [0.10550499 0.07536071 0.18086571 0.24115427 0.01507214 0.
  0.15072142]
 [0.18086571 0.21100999 0.18086571 0.22608213 0.27129856 0.16579356
  0.09043285]
 [0.2863707  0.25622642 0.25622642 0.2863707  0.13564928 0.19593785
  0.24115427]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
matrix_2 = np.random.randint(0, 10, (8, 10))

l = matrix_2.tolist()

min = 100
for i in l:
  if np.sum(i) < np.sum(min):
    min = i

print(min, l.index(min))

[2, 1, 4, 2, 5, 5, 0, 7, 1, 1] 6


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
vector1 = np.random.randint(0, 10, 10)
vector2 = np.random.randint(0, 10, 10)

print(np.linalg.norm(vector1-vector2))

10.954451150103322


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

X = np.matmul(np.linalg.inv(A), np.matmul(C, np.linalg.inv(B)))
X


array([[-1.00000000e+00, -2.44249065e-16],
       [ 2.00000000e+00, -1.00000000e+00],
       [-3.00000000e+00,  4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
data = np.loadtxt(r"/content/minutes_n_ingredients.csv", dtype=np.int32, delimiter=',', skiprows=1)

In [ ]:
data[::5]

array([[127244,     60,     16],
       [152828,     40,      7],
       [504666,     65,     20],
       ...,
       [  4747,      0,      9],
       [ 60756,     15,      5],
       [ 43407,     35,      7]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
print('Mean: ', data[::, 1].mean(), data[::, 2].mean())
print('Min: ', data[::, 1].min(), data[::, 2].min())
print('Max: ', data[::, 1].max(), data[::, 2].max())
print('Median: ', np.median(data[::, 1]), np.median(data[::, 2]))

Mean:  21601.00169 9.05528
Min:  0 1
Max:  2147483647 39
Median:  40.0 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
q = np.quantile(data[::, 1], 0.75)
print(data[data[::, 1] >= q])

[[504666     65     20]
 [280968     85     11]
 [ 99836    180      7]
 ...
 [287943     85     15]
 [498432     65     15]
 [ 81993    140     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
print(len(data[data[::, 1] == 0]))
data[data[::, 1] == 0] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
print(len(np.unique(data[::, 0])))

99522


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
uniq, counts = np.unique(data[::, 2], return_counts=True)
print(np.column_stack((uniq, counts)))

[[    1   492]
 [    2   924]
 [    3  2884]
 [    4  5479]
 [    5  7874]
 [    6  9328]
 [    7 10579]
 [    8 10887]
 [    9 10542]
 [   10  9548]
 [   11  8262]
 [   12  6574]
 [   13  4985]
 [   14  3639]
 [   15  2583]
 [   16  1760]
 [   17  1237]
 [   18   787]
 [   19   566]
 [   20   376]
 [   21   214]
 [   22   161]
 [   23   105]
 [   24    68]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
print(data[data[::, 2] >= 5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [287943     85     15]
 [498432     65     15]
 [ 81993    140     14]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [1]:
np.max(data[::, 2] / data[::, 1])

NameError: ignored

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
top_100 = -np.sort(-data, axis=0)[:100]
print(top_100[::, 2].mean())

28.22


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
data[np.random.choice(len(data), size=10, replace=False)]

array([[225730,     25,      8],
       [267253,    120,     15],
       [ 97063,      4,      8],
       [ 66883,     80,     11],
       [269121,     55,      9],
       [380936,     34,     14],
       [102260,     55,      8],
       [152345,     25,      9],
       [ 61102,     46,     10],
       [220669,     30,      7]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
mean = data[::, 2].mean()
print(len(data[data[::, 2] < mean]) / len(data) * 100)

58.989000000000004


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
type_time = []
for row in data[::, 1]:
  if row <= 20:
    type_time.append(1)
  else:
    type_time.append(0)

type_ing = []
for row in data[::, 2]:
  if row <= 5:
    type_ing.append(1)
  else:
    type_ing.append(0)

type_res = []

for i, k in zip(type_time, type_ing):
  if i==1==k:
    type_res.append([1])
  else:
    type_res.append([0])

type_res = np.array(type_res, dtype=np.int32)

new_data = np.append(data, type_res, axis=1)
print(new_data)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
print(len(new_data[new_data[::, 3]==1])/len(new_data)*100)

9.943


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
time_filter = []

for i in data[::, 1]:
  if i <= 10:
    time_filter.append(0)
  if i > 10 and i < 20:
    time_filter.append(1)
  if i >= 20:
    time_filter.append(2)

data_time_filter = np.array([[time_filter, data[::, 0]], [data[::, 1], data[::, 2]]])
data_time_filter

array([[[     2,      2,      0, ...,      2,      0,      2],
        [127244,  23891,  94746, ..., 498432, 370915,  81993]],

       [[    60,     25,     10, ...,     65,      5,    140],
        [    16,      7,      6, ...,     15,      4,     14]]])